config/routes.rb
Analytics1::Application.routes.draw do

  get "reports/getFormats/:mn", to: 'reports#getFormats'

  resources :rprocs
  resources :vtrs
  resources :reports
  resources :logs
  resources :periods

  get "welcome/index"

  resources :uploads, :periods, :reports, :analysis, :uplogs

  root :to => 'welcome#index'

  

end

app/models/rproc.rb
class Rproc < ActiveRecord::Base
  attr_accessible :description, :name, :active
end

app/controllers/rprocs_controller.rb
class RprocsController < ApplicationController
  # GET /rprocs
  # GET /rprocs.json
  def index
    @rprocs = Rproc.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rprocs }
    end
  end

  # GET /rprocs/1
  # GET /rprocs/1.json
  def show
    @rproc = Rproc.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rproc }
    end
  end

  # GET /rprocs/new
  # GET /rprocs/new.json
  def new
    @rproc = Rproc.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rproc }
    end
  end

  # GET /rprocs/1/edit
  def edit
    @rproc = Rproc.find(params[:id])
  end

  # POST /rprocs
  # POST /rprocs.json
  def create
    @rproc = Rproc.new(params[:rproc])

    respond_to do |format|
      if @rproc.save
        format.html { redirect_to @rproc, notice: 'Rproc was successfully created.' }
        format.json { render json: @rproc, status: :created, location: @rproc }
      else
        format.html { render action: "new" }
        format.json { render json: @rproc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rprocs/1
  # PUT /rprocs/1.json
  def update
    @rproc = Rproc.find(params[:id])

    respond_to do |format|
      if @rproc.update_attributes(params[:rproc])
        format.html { redirect_to @rproc, notice: 'Rproc was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rproc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rprocs/1
  # DELETE /rprocs/1.json
  def destroy
    @rproc = Rproc.find(params[:id])
    @rproc.destroy

    respond_to do |format|
      format.html { redirect_to rprocs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/rprocs_helper.rb
module RprocsHelper
end

app/views/rprocs/_form.html.erb
<%= form_for(@rproc) do |f| %>
  <% if @rproc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rproc.errors.count, "error") %> prohibited this rproc from being saved:</h2>

      <ul>
      <% @rproc.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :pdf_support %><br />
    <%= f.check_box :pdf_support %>
  </div>
  <div class="field">
    <%= f.label :csv_support %><br />
    <%= f.check_box :csv_support %>
  </div>
  <div class="field">
    <%= f.label :html_support %><br />
    <%= f.check_box :html_support %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rprocs/edit.html.erb
<h1>Editing rproc</h1>

<%= render 'form' %>

<%= link_to 'Show', @rproc %> |
<%= link_to 'Back', rprocs_path %>

app/views/rprocs/index.html.erb
<h1>Listing rprocs</h1>

<table border=0 cellspacing="3" cellpadding="3" style="border-width:1px;border-color:black;border-style:solid;">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Active?</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rprocs.each do |rproc| %>
  <tr>
    <td><%= rproc.name %></td>
    <td><%= rproc.description %></td>
    <td><%= rproc.active %></td>
    <td><%= link_to 'Show', rproc %></td>
    <td><%= link_to 'Edit', edit_rproc_path(rproc) %></td>
    <td><%= link_to 'Destroy', rproc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rproc', new_rproc_path %>

app/views/rprocs/new.html.erb
<h1>New rproc</h1>

<%= render 'form' %>

<%= link_to 'Back', rprocs_path %>

app/views/rprocs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @rproc.name %>
</p>

<p>
  <b>Description:</b>
  <%= @rproc.description %>
</p>

<p>
  <b>Module Name:</b>
  <%= @rproc.module_name %>
</p>

<p>
  <b>Active?</b>
  <%= @rproc.active %>
</p>

<p>
  <b>Support PDF Output?</b>
  <%= @rproc.pdf_support %>
</p>

<p>
  <b>Support CSV Output?</b>
  <%= @rproc.csv_support %>
</p>

<p>
  <b>Support HTML Output?</b>
  <%= @rproc.html_support %>
</p>


<%= link_to 'Edit', edit_rproc_path(@rproc) %> |
<%= link_to 'Back', rprocs_path %>