config/routes.rb
Analytics1::Application.routes.draw do

  get "reports/getFormats/:mn", to: 'reports#getFormats'

  resources :rprocs
  resources :vtrs
  resources :reports
  resources :logs
  resources :periods

  get "welcome/index"

  resources :uploads, :periods, :reports, :analysis, :uplogs

  root :to => 'welcome#index'

  

end

app/models/vtr.rb
class Vtr < ActiveRecord::Base
  attr_accessible :action, :comment, :date, :election, :form, :formNote, :jurisdiction, :leo, :notes, :voterid, :hashAlg
  def self.search(search)
    if search
      find(:all, :conditions => ['voterid LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/controllers/vtrs_controller.rb
class VtrsController < ApplicationController
  # GET /vtrs
  # GET /vtrs.json
  def index
    if !params[:search].nil? and !params[:search].empty?
      @vtrs = Vtr.search(params[:search])
    elsif !params[:recno].nil? and !params[:recno].empty?
      @vtrs = Vtr.find(:all,:offset => params[:recno], :limit => 20)
    else
      #@vtrs = Vtr.all
      @vtrs = Vtr.find(:all,:limit => 20)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vtrs }
    end
  end

  # GET /vtrs/1
  # GET /vtrs/1.json
  def show
    @vtr = Vtr.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vtr }
    end
  end

  # GET /vtrs/new
  # GET /vtrs/new.json
  def new
    @vtr = Vtr.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vtr }
    end
  end

  # GET /vtrs/1/edit
  def edit
    @vtr = Vtr.find(params[:id])
  end

  # POST /vtrs
  # POST /vtrs.json
  def create
    @vtr = Vtr.new(params[:vtr])

    respond_to do |format|
      if @vtr.save
        format.html { redirect_to @vtr, notice: 'Vtr was successfully created.' }
        format.json { render json: @vtr, status: :created, location: @vtr }
      else
        format.html { render action: "new" }
        format.json { render json: @vtr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vtrs/1
  # PUT /vtrs/1.json
  def update
    @vtr = Vtr.find(params[:id])

    respond_to do |format|
      if @vtr.update_attributes(params[:vtr])
        format.html { redirect_to @vtr, notice: 'Vtr was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vtr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vtrs/1
  # DELETE /vtrs/1.json
  def destroy
    @vtr = Vtr.find(params[:id])
    @vtr.destroy

    respond_to do |format|
      format.html { redirect_to vtrs_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/vtrs_helper.rb
module VtrsHelper
end

app/views/vtrs/_form.html.erb
<%= form_for(@vtr) do |f| %>
  <% if @vtr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vtr.errors.count, "error") %> prohibited this vtr from being saved:</h2>

      <ul>
      <% @vtr.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :voterid %><br />
    <%= f.text_field :voterid %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :leo %><br />
    <%= f.text_field :leo %>
  </div>
  <div class="field">
    <%= f.label :formNote %><br />
    <%= f.text_field :formNote %>
  </div>
  <div class="field">
    <%= f.label :form %><br />
    <%= f.text_field :form %>
  </div>
  <div class="field">
    <%= f.label :jurisdiction %><br />
    <%= f.text_field :jurisdiction %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_field :notes %>
  </div>
  <div class="field">
    <%= f.label :action %><br />
    <%= f.text_field :action %>
  </div>
  <div class="field">
    <%= f.label :election %><br />
    <%= f.text_field :election %>
  </div>
  <div class="field">
    <%= f.label :hashAlg %><br />
    <%= f.text_field :hashAlg %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vtrs/edit.html.erb
<h1>Editing vtr</h1>

<%= render 'form' %>

<%= link_to 'Show', @vtr %> |
<%= link_to 'Back', vtrs_path %>

app/views/vtrs/index.html.erb
<% bg = ''
   limit = 20
   index = 0
   index = params[:recno].to_i if !params[:recno].to_i.zero?
   count = 0
   max = Vtr.count()
 %>

<h2>Search Form</h2>
<%= form_tag(vtrs_path, :method => 'get') do %>
<table>
  <tr>
    <th>Voter ID search:</th>
    <td><%= text_field_tag :search, params[:search] %></td>
  </tr>
  <tr>
    <th>List Records starting at number:</th>
    <td><%= text_field_tag :recno, params[:recno] %> <cite>max is <%= max %></cite> </td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><%= submit_tag "Search", :name => nil %></td>
  </tr>
</table>
<% end %>

<br />

<h2>Listing A Maximum of <%= limit.to_s %> VTRs</h2>

<table>
  <tr>
    <th>&nbsp;</th>
    <th>Voterid</th>
    <th>Hash</th>
    <th>Create Date</th>
    <th>Jurisdiction</th>
    <th>Action</th>
    <th>Upload Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @vtrs.each do |vtr| %>
  <% if bg == ''
       bg = "lightgrey"
     else
       bg = ""
     end
     index += 1
     count += 1
     break if count > limit
   %>
  <tr bgcolor="<%= bg %>">
    <td align="right"><%= index %></td>
    <td><%= vtr.voterid %></td>
    <td><%= vtr.hashAlg %></td>
    <td><%= vtr.date.to_time.strftime("%m/%d/%Y %I:%T.%3N") %></td>
    <td><%= vtr.jurisdiction %></td>
    <td><%= vtr.action %></td>
    <td><%= vtr.created_at.to_time.strftime("%m/%d/%Y %I:%M%p") %></td>
    <td><%= link_to 'Show', vtr %></td>
    <td><%= link_to 'Edit', edit_vtr_path(vtr) %></td>
    <td><%= link_to 'Destroy', vtr, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vtr', new_vtr_path %>

app/views/vtrs/new.html.erb
<h1>New vtr</h1>

<%= render 'form' %>

<%= link_to 'Back', vtrs_path %>

app/views/vtrs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Voterid:</b>
  <%= @vtr.voterid %>
</p>

<p>
  <b>Date:</b>
  <%= @vtr.date %>
</p>

<p>
  <b>Leo:</b>
  <%= @vtr.leo %>
</p>

<p>
  <b>Formnote:</b>
  <%= @vtr.formNote %>
</p>

<p>
  <b>Form:</b>
  <%= @vtr.form %>
</p>

<p>
  <b>Jurisdiction:</b>
  <%= @vtr.jurisdiction %>
</p>

<p>
  <b>Comment:</b>
  <%= @vtr.comment %>
</p>

<p>
  <b>Notes:</b>
  <%= @vtr.notes %>
</p>

<p>
  <b>Action:</b>
  <%= @vtr.action %>
</p>

<p>
  <b>Election:</b>
  <%= @vtr.election %>
</p>

<p>
  <b>Hash Algorithm:</b>
  <%= @vtr.hashAlg %>
</p>


<%= link_to 'Edit', edit_vtr_path(@vtr) %> |
<%= link_to 'Back', vtrs_path %>