config/routes.rb
Analytics1::Application.routes.draw do

  get "reports/getFormats/:mn", to: 'reports#getFormats'

  resources :rprocs
  resources :vtrs
  resources :reports
  resources :logs
  resources :periods

  get "welcome/index"

  resources :uploads, :periods, :reports, :analysis, :uplogs

  root :to => 'welcome#index'

  

end

app/models/log.rb
class Log < ActiveRecord::Base
  attr_accessible :comment, :duperecs, :inrecs, :outrecs, :status, :filename, :fileCreateDate, :lowdate, :highdate, :idcount, :eventfreqs
  validates_presence_of :comment
  validates_presence_of :filename
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  # GET /logs
  # GET /logs.json
  def index
    @logs = Log.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @logs }
    end
  end

  # GET /logs/1
  # GET /logs/1.json
  def show
    @log = Log.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @log }
    end
  end

  # GET /logs/new
  # GET /logs/new.json
  def new
    @log = Log.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @log }
    end
  end

  # GET /logs/1/edit
  def edit
    @log = Log.find(params[:id])
  end

  # POST /logs
  # POST /logs.json
  def create
    @log = Log.new(params[:log])

    respond_to do |format|
      if @log.save
        format.html { redirect_to @log, notice: 'Log was successfully created.' }
        format.json { render json: @log, status: :created, location: @log }
      else
        format.html { render action: "new" }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /logs/1
  # PUT /logs/1.json
  def update
    @log = Log.find(params[:id])

    respond_to do |format|
      if @log.update_attributes(params[:log])
        format.html { redirect_to @log, notice: 'Log was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1
  # DELETE /logs/1.json
  def destroy
    @log = Log.find(params[:id])
    @log.destroy

    respond_to do |format|
      format.html { redirect_to logs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_form.html.erb
<%= form_for(@log) do |f| %>
  <% if @log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
      <% @log.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :file_name %><br />
    <%= f.date_select :filename %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :inrecs %><br />
    <%= f.number_field :inrecs %>
  </div>
  <div class="field">
    <%= f.label :outrecs %><br />
    <%= f.number_field :outrecs %>
  </div>
  <div class="field">
    <%= f.label :duperecs %><br />
    <%= f.number_field :duperecs %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logs/_show.html.erb
<p id="notice"><%= notice %></p>

<% # parse the events blob for later display
   events = Hash.new()
   eqs = @log.eventfreqs.split(/\^/)		# split into tag=val equations
   eqs.each do |eq|				# process each equation
     x = eq.split(/\<\>/)
     events[x[0]] = x[1] unless x[0].blank?
   end
 %>

<p>
  <b>File Name:</b>
  <%= @log.filename %>
</p>

<p>
  <b>Comment:</b>
  <%= @log.comment %>
</p>

<p>
  <b>File Creation Date:</b>
  <%= @log.fileCreateDate %>
</p>

<p>
  <b>Status:</b>
  <%= @log.status %>
</p>

<p>
  <b>Input records:</b>
  <%= @log.inrecs %>
</p>

<p>
  <b>Output records:</b>
  <%= @log.outrecs %>
</p>

<p>
  <b>Duplicate records:</b>
  <%= @log.duperecs %>
</p>

<p>
  <b>First VTR date:</b>
  <%= @log.lowdate %>
</p>

<p>
  <b>Last VTR date:</b>
  <%= @log.highdate %>
</p>

<p>
  <b>Count of Unique Voter IDs:</b>
  <%= @log.idcount %>
</p>

<p>
  <b>Event Frequencies:</b>
  <table>
  <%= eventString = ''
      bg = ''
      events.sort_by {|_k, v| v.to_i}.reverse.each do |key, val|
	if bg.empty?
	  bg = 'lightgrey'
	else
	  bg = ''
	end
        eventString += "<tr bgcolor=\"#{bg}\"><th align=\"right\">#{key}</th><td>#{val}</td></tr>"
      end
      raw(eventString)
  %>
  </table>
</p>

app/views/logs/edit.html.erb
<h1>Editing log</h1>

<%= render 'form' %>

<%= link_to 'Show', @log %> |
<%= link_to 'Back', logs_path %>

app/views/logs/index.html.erb
<h1>Listing Uploads</h1>

<table border=0 cellspacing="3" cellpadding="3" style="border-width:1px;border-color:black;border-style:solid;">
  <tr>
    <th>File Name</th>
    <th>Comment</th>
    <th>Uploaded</th>
    <th>Status</th>
    <th>Inrecs</th>
    <th>Outrecs</th>
    <th>Duperecs</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @logs.each do |log| %>
  <tr>
    <td><%= log.filename %></td>
    <td><%= log.comment %></td>
    <td><%= log.created_at %></td>
    <td><%= log.status %></td>
    <td align="right"><%= log.inrecs %></td>
    <td align="right"><%= log.outrecs %></td>
    <td align="right"><%= log.duperecs %></td>
    <td><%= link_to 'Show', log %></td>
    <td><%= link_to 'Edit', edit_log_path(log) %></td>
    <td><%= link_to 'Destroy', log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<!-- <%= link_to 'New Log', new_log_path %> -->
<%= link_to 'New Upload', '/uploads' %>

app/views/logs/new.html.erb
<h1>New log</h1>

<%= render 'form' %>

<%= link_to 'Back', logs_path %>

app/views/logs/show.html.erb
<%= render 'show' %>

<!-- <%= link_to 'Edit', edit_log_path(@log) %> | -->
<%= link_to 'Back', uploads_path %>