config/routes.rb
Analytics1::Application.routes.draw do

  get "reports/getFormats/:mn", to: 'reports#getFormats'

  resources :rprocs
  resources :vtrs
  resources :reports
  resources :logs
  resources :periods

  get "welcome/index"

  resources :uploads, :periods, :reports, :analysis, :uplogs

  root :to => 'welcome#index'

  

end

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessible :period, :module_name

  validates_presence_of :module_name
  validates_presence_of :period

  # global for dealing with reports
  Pnames = [] # will be filled-in at render time
  R2string = [1,'EAC Survey']
  String2r = [
               ['EAC Survey', 1]
             ]
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
    @report = Report.new
    @periods = Period.all # bfh: to support matching periods with reports
    @rprocs = Rproc.all # bfh: to support matching reports with report procedures

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reports }
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    logger.debug "*** in the show controller..."
    @report = Report.find(params[:id])
    @rprocs = Rproc.all # bfh: to support matching reports with report procedures
    @periods = Period.all # bfh: to support matching periods with reports

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @report }
    end

    @report.update_attribute(:updated_at, Time.now) 
  end

  # GET /reports/new
  # GET /reports/new.json
  def new
    @report = Report.new
    @periods = Period.all # bfh: to support matching periods with reports

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/1/edit
  def edit
    @periods = Period.all # bfh: to support matching periods with reports
    @rprocs = Rproc.all # bfh: to support matching reports with report procedures
    @report = Report.find(params[:id])
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(params[:report])
    @periods = Period.all # bfh: to support matching periods with reports
    @rprocs = Rproc.all # bfh: to support matching reports with report procedures

    flash[:report_format] = params[:report_format]

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render json: @report, status: :created, location: @report }
      else
        format.html { render action: "new" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reports/1
  # PUT /reports/1.json
  def update
    @report = Report.find(params[:id])

    respond_to do |format|
      if @report.update_attributes(params[:module_name])
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end

  #
  # BFH handle jQuery database query for form
  #
  def getFormats
      @rproc_data = Rproc.where(module_name: params[:mn]).first
      if @rproc_data.blank?
        render :text => "record_not_found"
      else
	tmp = Hash.new()
	tmp['pdf'] = @rproc_data.pdf_support;
	tmp['csv'] = @rproc_data.csv_support;
	tmp['html'] = @rproc_data.html_support;
        render :text => tmp.collect { |k, v| "#{k}:#{v}" }.join('~')
      end
    end
end

app/helpers/reports_helper.rb
module ReportsHelper

  # GenRept is a simple dispatch routine, calling report generation based on module name
  def GenRept(report)

    # parameter is a report job description
    rproc_key = report.module_name
    period_name = report.period

    format = params[:report_format]
    if format.nil? or format.empty? or format.blank?
      format = flash[:report_format]
    end
logger.debug "*** GenRept: params: " + params.inspect
logger.debug "*** GenRept: flash: " + flash.inspect

    # expand period name into parameters
    period = Hash.new()
    @periods.each do |tmp|
      if tmp.name == period_name
	period['ptype'] = tmp.ptype
	period['lodate'] = tmp.lodate
	period['hidate'] = tmp.hidate
	period['voter_reg_lodate'] = tmp.voter_reg_lodate
	period['voter_req_hidate'] = tmp.voter_reg_hidate
	break
      end
    end

    # call the class based on what the rproc says
    # This is where the report is being created!!! So must be source of error
    # Question is: does rproc_key exist?
    rpt = Object.const_get(rproc_key).new
    retval = rpt.generate(format,period)

    retval
  end

  #
  # these functions implement the reports
  #

  def get_report_items(period)
    # get a list of VTRs between these dates and make a hash of the formNote
    Vtr.where("date(date) between ? and ?", period['lodate'], period['hidate'])
  end
  module_function :get_report_items
end

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :module_name %><br />
    <%=
	# get the list of report procedures, sort by name, make an HTML select
	default_rp = nil
	rproclist = Hash.new()
	rproclist['-- choose a report--'] = ''
	@rprocs.each do |rproc|
	  rproclist[rproc['name']] = rproc['module_name'] if rproc.active?
	  default_rp = rproc['module_name'] if rproc['module_name'] === @report.module_name
	end

logger.debug @rprocs.inspect
logger.debug default_rp.inspect

	# make the HTML select
        f.select(
	  :module_name, 
	  options_for_select(
	    rproclist,
	    default_rp
	  ),
	  {},
	  {:onchange => "set_formats()"}
	)
     %>
  </div>
  <div class="field">
    <%= f.label :period %><br />
    <%=
	# get a hash of period names
	Report::Pnames.clear
	@periods.each do |p|
	    Report::Pnames << p.name
	end

	if params[:period].nil?
	  default_period = nil
	  sel_opt = {}
	else
	  default_period = params[:period]
	  sel_opt = {:disabled => true}
	end

	# create a select out of those period names
        f.select(
	  :period, 
	  options_for_select(
	    Report::Pnames,
	    default_period
	  ),
	  {},
	  sel_opt
	)
     %>
  </div>
  <div class="field">
    <%= f.label :output_format %><br />
    <%= radio_button_tag(:report_format, "pdf") %>
    <%= label_tag(:format_pdf, "PDF") %>
    <%= radio_button_tag(:report_format, "csv") %>
    <%= label_tag(:format_csv, "CSV") %>
    <%= radio_button_tag(:report_format, "html") %>
    <%= label_tag(:format_html, "HTML") %>
  </div>
  <div class="actions">
    <%= f.submit :onclick => "return validate_form()" %>
  </div>
<% end %>

app/views/reports/_noreports.html.erb
<h2>No Active Reports</h2>
<p>
There are no active reports to generate.
</p>

app/views/reports/edit.html.erb
<h1>Edit Report Job</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
      <h2><%=t('landing_page.reports')%></h2>
      <p><%=t('reports_page.text')%></p>

      <p>
<%
  status = flash[:status]
  if !status.nil?
    if status.include? "[0]"
        color = t('upload_page.ok_color')
        msg = 'OK'
    else
        color = t('upload_page.fail_color')
        msg = 'FAIL'
    end
  end

  # get the list of *active* report procedures so we can label report jobs correctly
  rproclist = Hash.new()
  @rprocs.each do |rproc|
    rproclist[rproc['module_name']] = rproc['name'] if rproc.active == true
  end

%>
  <span style="background-color: <%= color %>;"> <%= msg %> </span>
<%= flash[:status] %>
      </p>

<%= 
  # if there are no active reports, there is not much to do
  if rproclist.empty?
    render 'noreports'
  else
    render 'form' 
  end
%>

      <p>&nbsp;</p>
      <h3><%=t('reports_page.history_header')%></h3>

<table border=0 cellspacing="3" cellpadding="3" style="border-width:1px;border-color:black;border-style:solid;">
  <tr>
    <th>Report</th>
    <th>Period</th>
    <th>Created</th>
    <th>Last Run</th>
    <th><%= t('reports_page.make_button_text')%></th>
<!--
    <th></th>
    <th></th>
-->
    <th></th>
    <th></th>
  </tr>

<% @reports.each do |report| %>

<% # get the associated report procedure attributes
   gens = Array.new()
   base_path = reports_path
   base_path += '/'
   base_path += report.id.to_s
   base_path += '?'
   rproc = Rproc.where(module_name: report.module_name).first
   if !rproc.nil? and rproc['pdf_support'] == true
       gens.push(link_to "PDF", (base_path + 'report_format=pdf'))
   end
   if !rproc.nil? and rproc['csv_support'] == true
       gens.push(link_to 'CSV', (base_path + 'report_format=csv'))
   end
   if !rproc.nil? and rproc['html_support'] == true
       gens.push(link_to "HTML", (base_path + 'report_format=html'))
   end
   format_gen = '[' + gens.join(' | ') + ']'
 %>

  <tr>
    <td>
      <%= rproclist[report.module_name] %>
    </td>
    <td><%= report.period %></td>
    <td><%= report.created_at %></td>
    <td><%= report.updated_at %></td>
    <td><%= raw(format_gen) %></td>
<!--
    <td><%= link_to 'View', '' %></td>
    <td><%= link_to 'Show', report %></td>
-->
    <td><%= link_to 'Edit', edit_report_path(report) %></td>
    <td><%= link_to 'Remove', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/reports/new.html.erb
<h1>New report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<%
logger.debug "*** in the show view"
  # get the list of report procedures, sort by name, make an HTML select
  rproclist = Hash.new()
  @rprocs.each do |rproc|
    rproclist[rproc['module_name']] = rproc['name']
  end

  # if the admin has an overriding name, use that
  # default report name is whatever the programmer chose
  tkey = @report.module_name + '.report_title'
  rpt_name = t(tkey, :default => rproclist[@report.module_name])
 %>

<p>
  <b>Report:</b>
  <%= rpt_name %>
</p>

<p>
  <b>Period:</b>
  <%= @report.period %>
</p>

<p>
  <b>Output:</b>
</p>
<%= raw(GenRept(@report)) %>

<p><cite>Report Ends</cite></p>
<!-- <%= link_to 'Edit', edit_report_path(@report) %> | -->
<%= link_to 'Back', reports_path %>